// this file is generated by convert_test.go

package tw2s

import (
	"github.com/caiguanhao/opencc/configs"
	"github.com/caiguanhao/opencc/dicts/TSCharacters"
	"github.com/caiguanhao/opencc/dicts/TSPhrases"
	"github.com/caiguanhao/opencc/dicts/TWVariantsRev"
	"github.com/caiguanhao/opencc/dicts/TWVariantsRevPhrases"
)

const (
	Description = "Traditional Chinese (Taiwan standard) to Simplified Chinese"
)

var (
	Dicts = configs.Dicts{
		{
			TWVariantsRevPhrases.Dict,
			TWVariantsRev.Dict,
		},
		{
			TSPhrases.Dict,
			TSCharacters.Dict,
		},
	}
)
