// this file is generated by convert_test.go

package jp2t

import (
	"github.com/caiguanhao/opencc/configs"
	"github.com/caiguanhao/opencc/dicts/JPShinjitaiCharacters"
	"github.com/caiguanhao/opencc/dicts/JPShinjitaiPhrases"
	"github.com/caiguanhao/opencc/dicts/JPVariantsRev"
)

const (
	Description = "New Japanese Kanji (Shinjitai) to Traditional Chinese Characters (Kyūjitai)"
)

var (
	Dicts = configs.Dicts{
		{
			JPShinjitaiPhrases.Dict,
			JPShinjitaiCharacters.Dict,
			JPVariantsRev.Dict,
		},
	}
)
