// this file is generated by convert_test.go

package hk2t

import (
	"github.com/caiguanhao/opencc/configs"
	"github.com/caiguanhao/opencc/dicts/HKVariantsRev"
	"github.com/caiguanhao/opencc/dicts/HKVariantsRevPhrases"
)

const (
	Description = "Traditional Chinese (Hong Kong variant) to Traditional Chinese"
)

var (
	Dicts = configs.Dicts{
		{
			HKVariantsRevPhrases.Dict,
			HKVariantsRev.Dict,
		},
	}
)
