// this file is generated by convert_test.go

package opencc

import (
	"github.com/caiguanhao/opencc/configs"
	"github.com/caiguanhao/opencc/configs/hk2s"
	"github.com/caiguanhao/opencc/configs/hk2t"
	"github.com/caiguanhao/opencc/configs/jp2t"
	"github.com/caiguanhao/opencc/configs/s2hk"
	"github.com/caiguanhao/opencc/configs/s2t"
	"github.com/caiguanhao/opencc/configs/s2tw"
	"github.com/caiguanhao/opencc/configs/s2twp"
	"github.com/caiguanhao/opencc/configs/t2hk"
	"github.com/caiguanhao/opencc/configs/t2jp"
	"github.com/caiguanhao/opencc/configs/t2s"
	"github.com/caiguanhao/opencc/configs/t2tw"
	"github.com/caiguanhao/opencc/configs/tw2s"
	"github.com/caiguanhao/opencc/configs/tw2sp"
	"github.com/caiguanhao/opencc/configs/tw2t"
)

var (
	Dictionaries = map[string]string{
		"hk2s":  hk2s.Description,
		"hk2t":  hk2t.Description,
		"jp2t":  jp2t.Description,
		"s2hk":  s2hk.Description,
		"s2t":   s2t.Description,
		"s2tw":  s2tw.Description,
		"s2twp": s2twp.Description,
		"t2hk":  t2hk.Description,
		"t2jp":  t2jp.Description,
		"t2s":   t2s.Description,
		"t2tw":  t2tw.Description,
		"tw2s":  tw2s.Description,
		"tw2sp": tw2sp.Description,
		"tw2t":  tw2t.Description,
	}
)

func Convert(dictionary, in string) string {
	dicts := dictsForName(dictionary)
	return dicts.Convert(in)
}

func dictsForName(name string) configs.Dicts {
	if name == "hk2s" {
		return hk2s.Dicts
	}
	if name == "hk2t" {
		return hk2t.Dicts
	}
	if name == "jp2t" {
		return jp2t.Dicts
	}
	if name == "s2hk" {
		return s2hk.Dicts
	}
	if name == "s2t" {
		return s2t.Dicts
	}
	if name == "s2tw" {
		return s2tw.Dicts
	}
	if name == "s2twp" {
		return s2twp.Dicts
	}
	if name == "t2hk" {
		return t2hk.Dicts
	}
	if name == "t2jp" {
		return t2jp.Dicts
	}
	if name == "t2s" {
		return t2s.Dicts
	}
	if name == "t2tw" {
		return t2tw.Dicts
	}
	if name == "tw2s" {
		return tw2s.Dicts
	}
	if name == "tw2sp" {
		return tw2sp.Dicts
	}
	if name == "tw2t" {
		return tw2t.Dicts
	}
	return nil
}
