// this file is generated by dicts_test.go

package opencc

import (
	"github.com/caiguanhao/opencc/dicts/HKVariants"
	"github.com/caiguanhao/opencc/dicts/HKVariantsRev"
	"github.com/caiguanhao/opencc/dicts/HKVariantsRevPhrases"
	"github.com/caiguanhao/opencc/dicts/JPShinjitaiCharacters"
	"github.com/caiguanhao/opencc/dicts/JPShinjitaiPhrases"
	"github.com/caiguanhao/opencc/dicts/JPVariants"
	"github.com/caiguanhao/opencc/dicts/JPVariantsRev"
	"github.com/caiguanhao/opencc/dicts/STCharacters"
	"github.com/caiguanhao/opencc/dicts/STPhrases"
	"github.com/caiguanhao/opencc/dicts/TSCharacters"
	"github.com/caiguanhao/opencc/dicts/TSPhrases"
	"github.com/caiguanhao/opencc/dicts/TWPhrases"
	"github.com/caiguanhao/opencc/dicts/TWPhrasesRev"
	"github.com/caiguanhao/opencc/dicts/TWVariants"
	"github.com/caiguanhao/opencc/dicts/TWVariantsRev"
	"github.com/caiguanhao/opencc/dicts/TWVariantsRevPhrases"
	"github.com/liuzl/da"
)

var (
	Dictionaries = map[string]string{
		"hk2s":  "Traditional Chinese (Hong Kong standard) to Simplified Chinese",
		"jp2t":  "New Japanese Kanji (Shinjitai) to Traditional Chinese Characters (Kyūjitai)",
		"s2hk":  "Simplified Chinese to Traditional Chinese (Hong Kong standard)",
		"s2t":   "Simplified Chinese to Traditional Chinese",
		"s2tw":  "Simplified Chinese to Traditional Chinese (Taiwan standard)",
		"s2twp": "Simplified Chinese to Traditional Chinese (Taiwan standard, with phrases)",
		"t2hk":  "Traditional Chinese to Traditional Chinese (Hong Kong standard)",
		"t2jp":  "Traditional Chinese Characters (Kyūjitai) to New Japanese Kanji (Shinjitai)",
		"t2s":   "Traditional Chinese to Simplified Chinese",
		"t2tw":  "Traditional Chinese to Traditional Chinese (Taiwan standard)",
		"tw2s":  "Traditional Chinese (Taiwan standard) to Simplified Chinese",
		"tw2sp": "Traditional Chinese (Taiwan standard) to Simplified Chinese (with phrases)",
	}
)

func dictsForName(name string) [][]*da.Dict {
	if name == "hk2s" {
		return [][]*da.Dict{
			{
				HKVariantsRevPhrases.Dict,
				HKVariantsRev.Dict,
			},
			{
				TSPhrases.Dict,
				TSCharacters.Dict,
			},
		}
	}
	if name == "jp2t" {
		return [][]*da.Dict{
			{
				JPShinjitaiPhrases.Dict,
				JPShinjitaiCharacters.Dict,
				JPVariantsRev.Dict,
			},
		}
	}
	if name == "s2hk" {
		return [][]*da.Dict{
			{
				STPhrases.Dict,
				STCharacters.Dict,
			},
			{
				HKVariants.Dict,
			},
		}
	}
	if name == "s2t" {
		return [][]*da.Dict{
			{
				STPhrases.Dict,
				STCharacters.Dict,
			},
		}
	}
	if name == "s2tw" {
		return [][]*da.Dict{
			{
				STPhrases.Dict,
				STCharacters.Dict,
			},
			{
				TWVariants.Dict,
			},
		}
	}
	if name == "s2twp" {
		return [][]*da.Dict{
			{
				STPhrases.Dict,
				STCharacters.Dict,
			},
			{
				TWPhrases.Dict,
			},
			{
				TWVariants.Dict,
			},
		}
	}
	if name == "t2hk" {
		return [][]*da.Dict{
			{
				HKVariants.Dict,
			},
		}
	}
	if name == "t2jp" {
		return [][]*da.Dict{
			{
				JPVariants.Dict,
			},
		}
	}
	if name == "t2s" {
		return [][]*da.Dict{
			{
				TSPhrases.Dict,
				TSCharacters.Dict,
			},
		}
	}
	if name == "t2tw" {
		return [][]*da.Dict{
			{
				TWVariants.Dict,
			},
		}
	}
	if name == "tw2s" {
		return [][]*da.Dict{
			{
				TWVariantsRevPhrases.Dict,
				TWVariantsRev.Dict,
			},
			{
				TSPhrases.Dict,
				TSCharacters.Dict,
			},
		}
	}
	if name == "tw2sp" {
		return [][]*da.Dict{
			{
				TWPhrasesRev.Dict,
				TWVariantsRevPhrases.Dict,
				TWVariantsRev.Dict,
			},
			{
				TSPhrases.Dict,
				TSCharacters.Dict,
			},
		}
	}
	return nil
}
