// this file is generated by convert_test.go

package t2tw

import (
	"github.com/caiguanhao/opencc/configs"
	"github.com/caiguanhao/opencc/dicts/TWVariants"
)

const (
	Description = "Traditional Chinese to Traditional Chinese (Taiwan standard)"
)

var (
	Dicts = configs.Dicts{
		{
			TWVariants.Dict,
		},
	}
)
