// this file is generated by convert_test.go

package t2s

import (
	"github.com/caiguanhao/opencc/configs"
	"github.com/caiguanhao/opencc/dicts/TSCharacters"
	"github.com/caiguanhao/opencc/dicts/TSPhrases"
)

const (
	Description = "Traditional Chinese to Simplified Chinese"
)

var (
	Dicts = configs.Dicts{
		{
			TSPhrases.Dict,
			TSCharacters.Dict,
		},
	}
)
