// this file is generated by convert_test.go

package hk2s

import (
	"github.com/caiguanhao/opencc/configs"
	"github.com/caiguanhao/opencc/dicts/HKVariantsRev"
	"github.com/caiguanhao/opencc/dicts/HKVariantsRevPhrases"
	"github.com/caiguanhao/opencc/dicts/TSCharacters"
	"github.com/caiguanhao/opencc/dicts/TSPhrases"
)

const (
	Description = "Traditional Chinese (Hong Kong variant) to Simplified Chinese"
)

var (
	Dicts = configs.Dicts{
		{
			HKVariantsRevPhrases.Dict,
			HKVariantsRev.Dict,
		},
		{
			TSPhrases.Dict,
			TSCharacters.Dict,
		},
	}
)
