// this file is generated by convert_test.go

package t2jp

import (
	"github.com/caiguanhao/opencc/configs"
	"github.com/caiguanhao/opencc/dicts/JPVariants"
)

const (
	Description = "Traditional Chinese Characters (Kyūjitai) to New Japanese Kanji (Shinjitai)"
)

var (
	Dicts = configs.Dicts{
		{
			JPVariants.Dict,
		},
	}
)
