// this file is generated by convert_test.go

package tw2t

import (
	"github.com/caiguanhao/opencc/configs"
	"github.com/caiguanhao/opencc/dicts/TWVariantsRev"
	"github.com/caiguanhao/opencc/dicts/TWVariantsRevPhrases"
)

const (
	Description = "Traditional Chinese (Taiwan standard) to Traditional Chinese"
)

var (
	Dicts = configs.Dicts{
		{
			TWVariantsRevPhrases.Dict,
			TWVariantsRev.Dict,
		},
	}
)
