// this file is generated by convert_test.go

package t2hk

import (
	"github.com/caiguanhao/opencc/configs"
	"github.com/caiguanhao/opencc/dicts/HKVariants"
)

const (
	Description = "Traditional Chinese to Traditional Chinese (Hong Kong variant)"
)

var (
	Dicts = configs.Dicts{
		{
			HKVariants.Dict,
		},
	}
)
